### PR TITLE
Fix bug in _is_reachable()

### PR DESCRIPTION
**Pull request by mbforbes**
Some code was not indented and so was not actually part of the method, I think.

### CODE REVIEW

**Comment by trainman419** [comment]
Have you had a chance to test this on a PR2 or in simulation?

**Comment by mbforbes** [comment]
I'm testing in simulation... it doesn't affect the behavior, just causes the extra message to be logged. This is somewhat confounding to me, as it seems like the indentation error would prevent the function from returning a value. I sent the pull request because it definitely seemed to be a bug, and was curious why it was working.

**Comment by trainman419** [comment]
This probably worked because, lacking a return statement, python returns None, and _is_reachable() was being checked only for truthiness elsewhere.

It probably resulted in all of the relevant markers being colored as "unreachable"

**Comment by mbforbes** [comment]
What's weird is the coloring was working properly without this fix... replacing the line with `if False:` makes them all grey instead.

**Pull request merged**
